### ISSUE TITLE
thr under process_result in test script incorrect

### ISSUE THREAD

**Issue by yipcma** [JoaoPauloAires/potential-conflict-identifier#1]
Running the test script results in the following error:
```
Traceback (most recent call last):
  File "test_conflict_finder.py", line 134, in <module>
    tcf.test_identifier()
  File "test_conflict_finder.py", line 59, in test_identifier
    self.process_contract(contract_path, new_contract_path)
  File "test_conflict_finder.py", line 72, in process_contract
    self.process_result(potential_conflicts, inserted_conflicts)
  File "test_conflict_finder.py", line 105, in process_result
    print "Something's wrong, I don't know this threshold %.1f!!!" % p_conflict[
0]
TypeError: float argument required, not str
```
Issue: line 85 in test script `thr = p_conflict[0]`, where `print p_conflict` gives: 

```
('Customer will be responsible for restocking charges or freight cost incurred i
n connection with Dead Inventory.', 'Customer may be responsible for restocking
charges or freight cost incurred in connection with Dead Inventory.', 1, 'Type 2
')
```

Problem: thr is not recorded in the result.

**Comment by JoaoPauloAires** [comment]
Hi, @yipcma!
Sorry for the delay! Thanks for noticing this mistake.
I solved it in my last commit: 9631f8edb1a92ecf29918d5be1cdeea23afe3061

Thanks again!
